#!/bin/bash
# Runs during `blueprint -export`, just before the .blueprint file is packaged.
#
# Nothing to do: everything shipped in the package is already in the repository,
# and the egg is not part of the extension (an admin imports it separately), so
# there is no generated artifact to refresh at export time.
#
# egg/modpack-installer.json is regenerated by egg/build_egg.py during
# development instead — the egg directory is not present in the build tree, so
# it could not be regenerated from here even if that were wanted.
#
# It must exit 0. A non-zero exit here fails the export.

exit 0
